### ISSUE TITLE
support for required includes

### ISSUE THREAD

**Issue by cosminbasca** [chimpler/pyhocon#113]
Hi guys, 

Required includes do not seem to be supported. I am adding a ling of the form:
`include required("foo.conf")`, and am getting back a parsing exception:

`pyparsing.ParseSyntaxException: Expected {Forward: ... | {{{"=" | ":" | "+="} - [Suppress{{{"#" | "//"} - SkipTo{Suppress:(W)) | StringEnd})} | Suppress:(W))})]...} - ConcatenatedValueParser[{Suppress{[Suppress:(W,))] {"#" | "//"} - SkipTo{Suppress:(W)) | StringEnd})}) | {Suppress"include") {Re'".*?"[ \t]*') | {{{{"url" | "file"} - Suppress"(")} - Re'".*?"[ \t]*')} - Suppress")")}}} | Re'[ \t]*\\$\\{[^\\}]+\\}[ \t]*') | Forward: ... | Forward: ... | Re'[+-]?(\\d*\\.\\d+|\\d+(\\.\\d+)?)([eE]\\d+)?(?=$|[ \t]*([\\$\\}\\],#\n\r]|//))') | "true" | "false" | "null" | Re'""".*?"""') | Re'".*?"[ \t]*') | Re'(?:\\\\|[^\\[\\{\\s\\]\\}#,=\\$])+[ \t]*') | Suppress{"\" - Suppress:(W))})}]...)}} (at char 16), (line:1, col:17)`

**Comment by darthbear** [comment]
Implemented in `pyhocon==0.3.37`. Thanks for the feature request @cosminbasca!
