### ISSUE TITLE
triple quoted string parsing bug

### ISSUE THREAD

**Issue by farquet** [chimpler/pyhocon#118]
On the latest version (0.3.35), the multiline string feature is buggy. The [official documentation](https://github.com/typesafehub/config/blob/master/HOCON.md#multi-line-strings) says : 

> In Python, """foo"""" is a syntax error (a triple-quoted string followed by a dangling unbalanced quote). In Scala, it is a four-character string foo". HOCON works like Scala; any sequence of at least three quotes ends the multi-line string, and any "extra" quotes are part of the string.

This doesn't work properly if we have such a value in a array.
Let's take an example : 
```
a : ["""foo"""",
     "bar"]
```
successfully gives (using `pyhocon -i test.hocon`) : 
```
{
  "a": [
    "foo\"",
    "bar"
  ]
}
```
But, if the triple quoted value is on the same line as subsequent items, parsing is incorrect : 
```
a : ["""foo"""", "bar"]
```
gives : 
```
{
  "a": [
    "foo, bar\""
  ]
}
```

**Comment by darthbear** [comment]
Pushed to `pyhocon==0.3.36`. Thanks @farquet for the detailed bug report!
