### ISSUE TITLE
String substitution broken?

### ISSUE THREAD

**Issue by eric239** [chimpler/pyhocon#12]
Could it be that the fix for object merging (issue #10) broken string substitution?
Expanding on the simple unit test from pyhocon codebase:
```
In [54]: config = ConfigFactory.parse_string(
   ....:             """
   ....:             {
   ....:                 a: {
   ....:                     b: {
   ....:                         c = buzz
   ....:                     }
   ....:                 }
   ....:                 d = test ${a.b.c} me
   ....:                 e = ${a.b.c} me
   ....:             }
   ....:             """
   ....:         )

In [55]: config['d']
Out[55]: 'test buzzme'

In [56]: config['e']
Out[56]: 'buzz'
```
Whereas I expected to get `test buzz me` (with the space between subst expr and the last string) and `buzz me` (here the appended string got lost entirely)

Let me know if I'm misunderstanding how string subst is supposed to work.

**Comment by darthbear** [comment]
I think this is a bug. Probably due to the changes I made this week end. I'll work on it tonight.

**Comment by darthbear** [comment]
Hi eric239, I just pushed the fix to pypi. `pyhocon==0.2.6`. Let me know if you find any other issues. Thanks!
