### ISSUE TITLE
Incorrect merging of config trees

### ISSUE THREAD

**Issue by tkrodriguez** [chimpler/pyhocon#157]
I'm attempting to override an environment variable in an earlier definition with some very complex composition but in certain contexts I get a different order of merging.  I've boiled it down to a relatively simple case.   All the arrays at the end should have the same contents but the last element of b2 has the wrong value.
```
common : {
}

b1 = []

var = "wrong"

compilerCommon : ${common} {
    VAR : ${var}
}

substrate-suite: {
    VAR  : "right"
}
b1 = [
  ${compilerCommon} ${substrate-suite}
  ${compilerCommon} ${substrate-suite}
]

b2 = [
  ${compilerCommon} ${substrate-suite}
  ${compilerCommon} ${substrate-suite}
]
```

```
>>> tree = ConfigParser.parse(open('ci.hocon').read())
>>> tree.get('b1')
[ConfigTree([('VAR', 'right')]), ConfigTree([('VAR', 'wrong')])]
>>> tree.get('b2')
[ConfigTree([('VAR', 'right')]), ConfigTree([('VAR', 'right')])]
```

All the elements in the hocon file seem to be required to make it appear.  Assign the variable first and then replacing it seems to be required.

**Comment by aalba6675** [comment]
@tkrodriguez  are you able to test https://github.com/aalba6675/pyhocon/tree/fix-issue-157 on your reproducer and your actual use case?

If it fixes both then I think I know what is going wrong. Thank you.

**Comment by tkrodriguez** [comment]
Yes that seems to fix the problem.  Sorry I didn't reply sooner.  The github message got filtered into a folder.  Thanks!
