### ISSUE TITLE
ParseSyntaxException thrown on valid hocon (caused by forward slash '/' character)

### ISSUE THREAD

**Issue by richard534** [chimpler/pyhocon#165]
Currently pyhocon will throw an exception when it encounters a key beginning with a forward slash.
Keys beginning with forward slashes are valid hocon.
They are also commonly used in akka hocon configuration files e.g:
```
akka {
  actor {
    provider = "local"
    deployment {
      /loaderSupervisor/s3SinkActor {
        router = round-robin-pool
        nr-of-instances = 20
      }
    }
  }
}
```

Recreation steps:
```
file = open('akka-hocon') # file containing above snippet
file_contents = file.read()
hocon_object = ConfigFactory.parse_string(file_contents)
```

**Comment by darthbear** [comment]
Thank you @richard534! It's now fixed in `pyhocon==0.3.43`
