### ISSUE TITLE
Allow specification of indentation in HOCONConverter

### ISSUE THREAD

**Issue by davidtwco** [chimpler/pyhocon#168]
When using `HOCONConverter` to write data, it would be nice to be able to specify the indentation of the string generated (ie. two spaces, four spaces, a tab, etc).

**Comment by Dominik1123** [comment]
You can do so by specifying the `indent` keyword. For example: `HOCONConverter.to_json(config, indent=4)`. You need to specify an integer here, but it's anyway better to use spaces instead of tabs.

**Comment by davidtwco** [comment]
Thanks, not sure how I didn't notice that before!
