### ISSUE TITLE
Parsing exception for a list with an EOL

### ISSUE THREAD

**Issue by silviuvergoti** [chimpler/pyhocon#21]
Code:
from pyhocon import ConfigFactory
c = ConfigFactory.parse_string('values :\n[\n"null",\n"undefined",\n"0",\n]\n')

This is throwing the following exception :
  File "/pyhocon/__init__.py", line 60, in parse_string
    return ConfigParser().parse(content, basedir)
  File "/pyhocon/__init__.py", line 197, in parse
    config = config_expr.parseString(content, parseAll=True)[0]
  File "/pyparsing.py", line 1125, in parseString
    raise exc
pyparsing.ParseException: Expected end of text (at char 9), (line:2, col:1)

Please compare with the working example, when using Egyptian brackets (no \n between ":" and "["):

c = ConfigFactory.parse_string('values : [\n"null",\n"undefined",\n"0",\n]\n')

**Comment by darthbear** [comment]
Thanks again for the bug report. It's pushed to pypi `pyhocon==0.3.3`
