### ISSUE TITLE
How to use pyhocon to validate hocon in cli?

### ISSUE THREAD

**Issue by zanhsieh** [chimpler/pyhocon#23]
Hi,

The user could validate a json file or anything could pipe in cli as:

$ echo '{"foo":1, "bar":2}' | python -m json.tool
{
    "bar": 2, 
    "foo": 1
}

Just curious how to do it with pyhocon. Thanks.

**Comment by darthbear** [comment]
Hi,

We don't have anything to validate but you convert the hocon file to a json file:
```
echo '{foo=1, bar:2}' | pyhocon
```
(by default it converts to json). If you don't have any error it should be a valid pyhocon file.

You can type `pyhocon -h` for more info.
