### ISSUE TITLE
Wrong Order in Substitution Resolution Leads to Faulty Configuration

### ISSUE THREAD

**Issue by sbachstein** [chimpler/pyhocon#271]
The substitution resolution is not performed in the order of the HOCON variable assignment.

Version: 0.3.58

Example:

`pyhocon -i <INPUT_FILE>`

Input file:
```ini
common = common
original = ${common}/original
result = ${original}
replaced = ${common}/replaced
result = ${replaced}
copy = ${result}
```

Result:
```json
{
  "common": "common",
  "original": "common/original",
  "result": "common/replaced",
  "replaced": "common/replaced",
  "copy": "common/original"
}
```

Expected Result:
```json
{
  "common": "common",
  "original": "common/original",
  "result": "common/replaced",
  "replaced": "common/replaced",
  "copy": "common/replaced"
}
```

Analyzing the substitution process, we see that the substitution is performed in the following order:
1. ${common} -> original = common/original
2. ${original} -> result = common/original
3. ${replaced} -> result = ${replaced} (HOWEVER: cannot be resolved because ${replaced} contains a substitution itself, thus the previous resolution stays for now! Here lies the issue!)
4. ${common} -> replaced = common/replaced
5. ${result} -> copy = common/original (Because the result = ${replaced} substitution could not be done until now, this apparently takes the previous substitution)

Now the next substitution iteration starts with the single left over substitution:
1. ${replaced} -> result = common/replaced

**Comment by sbachstein** [comment]
I am not entirely sure what you are suggesting: Are you saying the actual behavior is according to spec or are you saying the behavior that I am expecting is according to spec?

I have checked this with https://hocon-playground.herokuapp.com/ which uses the java implementation and it confirms my expectations.

While this minimal example may look synthetic because you would not have duplicate keys within the same scope, it is absolutely possible for this to happen using includes or merging two configs.

For example when using a common configuration file that is merged with an environment-specific config file where values from the common configuration are potentially overwritten.

**Comment by afanasev** [comment]
Still not good though, I see cases working wrong.

**Comment by afanasev** [comment]
Better now: https://github.com/chimpler/pyhocon/pull/285
