### ISSUE TITLE
Is += working at all?

### ISSUE THREAD

**Issue by ws1088** [chimpler/pyhocon#281]
test.conf:
```conf
foo {
    baz = ["a"]
    baz += "b"
}
```

code:
```py
from pyhocon import ConfigFactory
spec = ConfigFactory.parse_file('./test.conf'))
print(spec)

```

output:
```
ConfigTree([('foo', ConfigTree([('baz', ' b')]))])
```

I thot `+=` will concatenate...

**Comment by USSX-Hares** [comment]
Actually, it DOES concatenate... If you create the following config, the `+=` would work... but NOT as intended:
```pyhocon
baz = ["a"]
foo {
    baz += "b"
}
```

**Comment by USSX-Hares** [comment]
Also, according to https://hocon-playground.herokuapp.com/, the `+=` operator SHOULD NOT extend arrays, only append elements, which, ironically, pyhocon can't do.

**Comment by ws1088** [comment]
thanks!
