### ISSUE TITLE
Config can't have keys with dots in them.

### ISSUE THREAD

**Issue by agnibha** [chimpler/pyhocon#3]
Although doesn't really affect too much, a single key can't contain dots(.). In typesafe, such cases are possible with quotes enclosed keys.

**Comment by darthbear** [comment]
Hello, can you give an example of keys with dots in them? Thanks.

**Comment by agnibha** [comment]
it could be like this:

settings_for_sites : {
    "general" : {
        input = "Nothing"
    }
    "www.abc.com" : {
        input = ""
    }
    "www.bcd.com" : {
        input = "something"
    }
}

Listing children of "settings_for_sites" should give: [ general, www.abc.com, www.bcd.com ].

Ignore if this doesn't make sense.

**Comment by darthbear** [comment]
Thank you for your detailed answer! I just implemented it so in your case you have:
```
> config['settings_for_sites']
OrderedDict([('general', OrderedDict([('input', 'Nothing')])), ('www.abc.com', OrderedDict([('input', '')])), ('www.bcd.com', OrderedDict([('input', 'something')]))])

Examples of usages:
```
config['settings_for_sites."general".input']
config['settings_for_sites.general.input']
config['settings_for_sites."www.abc.com"']
config['settings_for_sites']
```
Note that "general" can be quoted or not in the path (because the quoted key does not contain a dot).

Thanks again for reporting that issue! :-)

**Comment by onilton** [comment]
I don't know if this is a regression, but keys with `" "` appears at the dict 
```
ConfigTree([('general', ConfigTree([('input', 'Nothing')])), ('"www.abc.com"', ConfigTree([('input', '')])), ('"www.bcd.com"', ConfigTree([('input', 'something')]))])
```
