### ISSUE TITLE
isinstance(config, str) will fail on 2.x

### ISSUE THREAD

**Issue by felixbr** [chimpler/pyhocon#44]
I've tried to parse a config like this:

    config = ConfigFactory.parse_file('path1').with_fallback('path2')

`with_fallback` takes either a `ConfigTree` or a string. It is testing this with `isinstance(config, str)`, but this only works correctly in Python 3.x. In my case (2.7) it interpreted `'path2'` as a ConfigTree which crashes with a parse-error obviously.

The best way of supporting this in 2.x and 3.x simultaneously is probably the library `six` which you can see in this answer: http://stackoverflow.com/questions/11301138/how-to-check-if-variable-is-string-with-python-2-and-3-compatibility

Of course you could also just reverse the if-clause by checking for a `ConfigTree` object instead.

You should also consider checking if there are other locations in your code where checking for a string occurs.

I can fix it myself and submit a pullrequest if you tell me what's your decision, of course. :)

**Comment by darthbear** [comment]
Hi @felixbr. Thanks for the comment. Yes, I think your idea of reversing the if-clause is a good idea.

Thanks.

Francois
