### ISSUE TITLE
Substitutions don't work correctly.

### ISSUE THREAD

**Issue by vamega** [chimpler/pyhocon#48]
The following example, taken from the typesafe config [README](https://github.com/typesafehub/config#user-content-inheritance) will not result in the expected config.
```
data-center-generic = { cluster-size = 6 }
data-center-east = ${data-center-generic}
data-center-east = { name = "east" }
data-center-west = ${data-center-generic}
data-center-west = { name = "west", cluster-size = 8 }
```

Instead of data-center-east being extended to have the a name key in addition to the cluster-size key, the old keys are removed and only the name key is remaining.

This can be verified by using the included tool.

**Comment by darthbear** [comment]
Hi @vamega, thanks you for the bug report and sorry for the delay in getting back to you. This should be fixed in the new release `python==0.3.13`. Thanks!
