### ISSUE TITLE
String substitution does not work in merged lists/dicts

### ISSUE THREAD

**Issue by alexey-terentiev** [chimpler/pyhocon#50]
Config:

    application.foo = 128m
    application.default-jvm-opts = [-XX:+UseParNewGC]
    application.large-jvm-opts = ${application.default-jvm-opts} [-Xm16g, ${application.foo}]

Code:

    conf = ConfigFactory.parse_file('some.conf')
    print(conf["application.large-jvm-opts"])

Result:

    ['-XX:+UseParNewGC', '-Xm16g', [ConfigValues: [ConfigSubstitution: application.foo]]]

Expected result:

    ['-XX:+UseParNewGC', '-Xm16g', '128m']

**Comment by alexey-terentiev** [comment]
Hi. Any hope there will be a quick fix?
I'm trying to switch some automation tools from groovy to python and I'm used to typesafe. So this is n1 configuration framework for me atm. Frankly, I don't like all others. Tried to look through the code but didn't get what's wrong with it. It's kinda showstopper for me.
Thank you.

**Comment by darthbear** [comment]
Hello,

Thanks for the bug report. This should now be fixed in `pyhocon==0.3.12`.

Thanks.

Francois
