### ISSUE TITLE
pyhocon is missing the argparse dependency when installed for Python 2.6

### ISSUE THREAD

**Issue by movermeyer** [chimpler/pyhocon#53]
When you install pyhocon for Python 2.6:

    pip install pyhocon

It does not download the ['argparse'](https://pypi.python.org/pypi/argparse) dependency automatically. Note that this library is included in the standard library for Python >= 2.7 and >= 3.2

If you try to use the pyhocon library without it, you get:

    >>> import pyhocon
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/usr/lib/python2.6/site-packages/pyhocon/__init__.py", line 5, in <module>
        from .tool import HOCONConverter  # noqa
      File "/usr/lib/python2.6/site-packages/pyhocon/tool.py", line 1, in <module>
        import argparse
    ImportError: No module named argparse

It seems that pyhocon supports Python 2.6, given that the package is in the [Python 2.6 pypi category](https://pypi.python.org/pypi?:action=browse&c=531).

**Comment by darthbear** [comment]
Thanks @movermeyer for the fix!

**Comment by movermeyer** [comment]
Thanks @darthbear for being so responsive.
