### ISSUE TITLE
substitution is not working if variable is set to override using environment variable

### ISSUE THREAD

**Issue by pvshewale** [chimpler/pyhocon#66]
below is the example given on readme page

```
{
  databases {
    "mysql" = {
      host = "abc.com" # change it
      port = 3306 # default
      username: scott // can use : or =
      password = tiger, // can optionally use a comma
      // number of retries
      retries = 3
    }
  }

# you can use substitution with unquoted strings
  retries_msg = You have ${databases.mysql.retries} retries

  # retries message will be overriden if environment variable CUSTOM_MSG is set
  retries_msg = ${?CUSTOM_MSG}
}
```

Variable `retries_msg` is used substitution and same is also set to be overridden using environment variable. With this config file and environment variable `CUSTOM_MSG` is NOT set, parse file and try to get `retries_msg`

```
>>> from pyhocon import ConfigFactory
>>> conf = ConfigFactory.parse_file('database.conf')
>>> conf.get('retries_msg')
[ConfigValues: You have ,[ConfigSubstitution: databases.mysql.retries],retries]
```

As shown above it fails to do the substitution. in case we do not use overriding using  environment variable, it works as expected.

**Comment by darthbear** [comment]
Hi @pvshewale. Thank you for the bug report. It's fixed in the PR https://github.com/chimpler/pyhocon/pull/69 and we released it as `pyhocon==0.3.19`. Thanks!
