### ISSUE TITLE
values with quotes are not escaped properly

### ISSUE THREAD

**Issue by ethanlu** [chimpler/pyhocon#96]
I had a configuration file where a property contained a piece of string that had a double quote in it, but pyhocon was not able to parse it correctly. Here is a breakdown of the issue:

if I have a configuration file like so:

```
// test.conf
{
    test {
        foo = abc"def
        bar = "abc\"def"
        foobar = "abc"def"
    }
}
```

parse it into Pyhocon and print out the values:

```
config = ConfigFactory.parse_file('test.conf')
print(config['test']['foo'])
print(config['test']['bar'])
print(config['test']['foobar'])
```

I get as output:

```
'abc"def'
'abc\\def"'
'abcdef"'
```

The first output is correct, but the second and third is not. This was done in Python 3.4.3 btw.

**Comment by darthbear** [comment]
Sorry for the delay @ethanlu. This should be addressed in `pyhocon==0.3.41`. 
In HOCON, only the followings are correct:
```
a = "abc\"test" => abc"test
b = "abc""cde" => abccde
c = abc\"cde => abc"cde
```

The followings are invalid:
```
a = abc"cde => This string is invalid because it starts as an unquoted string (abc) followed by a quoted string that doesn't end.
b = "abc"cde" => The first string is "abc" and the second one is starting as an unquoted string cde followed by an empty quoted string that doesn't end
```
