### ISSUE TITLE
Checking if item is in configuration

### ISSUE THREAD

**Issue by NickG123** [chimpler/pyhocon#97]
It appears that __contains__ is not overridden in ConfigTree, so checking for the existence of a key does not work if it is dot-separated:

``` python
>>> from pyhocon import ConfigFactory
>>> t = ConfigFactory.from_dict({"test": {"test": 1}})
>>> "test.test" in t
False
>>> t.get_int("test.test")
1
```

**Comment by darthbear** [comment]
Thanks for reporting that issue @NickG123. Just implemented it and pushed it to `pyhocon==0.3.35`. Thanks!
